version: "1.1"

services:
  mongo:
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INTITD_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: testpassword

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGO_INTITD_ROOT_USERNAME: development
      ME_MONGO_INTITD_ROOT_USERNAME: development
      ME_CONFIG_MONGODB_URL: mongodb://development:testpassword@mongo:27017/
